name: Build and Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - name: Linux
            platform: linux
            os: ubuntu-latest
            configure-options: ''
          - name: Windows
            platform: windows
            os: windows-latest
            configure-options: -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
          - name: macOS x86_64
            platform: macos_x86_64
            os: macos-13
            configure-options: -DCMAKE_OSX_ARCHITECTURES=x86_64
          - name: macOS arm64
            platform: macos_arm64
            os: macos-latest
            configure-options: -DCMAKE_OSX_ARCHITECTURES=arm64
      
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -S . -B build ${{ matrix.configure-options }} && cmake --build build --config Release
      
      - name: Package
        run: |
          cd build
          cpack -C Release
          
      - name: Upload Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: libtransformersphp-${{  github.ref_name }}-${{ matrix.platform }}
          path: build/*.tar.gz
    
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:2023-05-03
          cpu: cortex-a53
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
          bind_mount_repository: true
          commands: |
            sudo apt-get update -y
            sudo apt-get install -y cmake
            
            cmake -S . -B build && cmake --build build --config Release
            cd build
            cpack -C Release
            
      - name: Upload Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
            name: libtransformersphp-${{  github.ref_name }}-linux-arm64
            path: build/*.tar.gz
          
  release:
    needs: 
      - build
      - build-linux-arm64
    
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: libs
          pattern: libtransformersphp-*
          merge-multiple: true
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            libs/*